# Generated by Django 4.1.4 on 2022-12-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_app', '0002_advertisement_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Viewed', 'Viewed'), ('Interview Phase', 'Interview Phase'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Waiting', max_length=25),
        ),
    ]
