# Generated by Django 4.1.4 on 2022-12-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_app', '0003_alter_appliedjobs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='job_type',
            field=models.CharField(choices=[('FULL TIME', 'FULL TIME'), ('PART TIME', 'PART TIME'), ('INTERN', 'INTERN'), ('REMOTE', 'REMOTE'), ('HYBRID', 'HYBRID')], max_length=50),
        ),
    ]
