# Generated by Django 4.1.4 on 2022-12-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_app', '0004_alter_advertisement_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('Graduated', 'Graduated'), ('Experienced', 'Experienced')], default='Junior', max_length=50),
        ),
    ]
