# Generated by Django 4.1.4 on 2022-12-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_app', '0006_alter_advertisement_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='job_type',
            field=models.CharField(choices=[('Tam Zamanlı', 'Tam Zamanlı'), ('Yarı Zamanlı', 'Yarı Zamanlı'), ('Stajer', 'Stajer'), ('Uzaktan', 'Uzaktan'), ('Hibrit', 'Hibrit')], default='Full Time', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('Çaylak', 'Çaylak'), ('Middle', 'Middle'), ('Kıdemli', 'Kıdemli'), ('Mezun', 'Mezun'), ('Tecrübeli', 'Tecrübeli')], default='Junior', max_length=50),
        ),
    ]
