# Generated by Django 4.1.4 on 2022-12-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_applicant_birth_date_alter_employer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
